version: "3.8"

services:
  redis:
    image: redis:alpine
  rank-counter:
    image: redis:alpine
    depends_on:
      - redis
    command:
      - redis-cli
      - -h
      - redis
      - set
      - rank-counter
      - ${REPLICAS}
  max-runs:
    image: redis:alpine
    depends_on:
      - redis
    command:
      - redis-cli
      - -h
      - redis
      - set
      - max-runs
      - ${MAX_RUNS}
  sweep:
    image: ethanabrooks/create-sweep:latest
    depends_on:
      - redis
    volumes:
      - .:/config
    command:
      - --config=/config/config.yml
      - --graphql-endpoint=${GRAPHQL_ENDPOINT}
      - --name=${NAME}
      - --project=gpt-rl
      - --method=${SWEEP_METHOD}
      - redis
  agent:
    build: .
    depends_on:
      - rank-counter
      - max-runs
      - sweep
    entrypoint:
      - execute-sweep
      - --graphql-endpoint=${GRAPHQL_ENDPOINT}
      - --command=python ${SCRIPT} sweep --graphql_endpoint=${GRAPHQL_ENDPOINT} --host_machine=${HOST_MACHINE} --sweep
    volumes:
      - "${PWD}/logs:/tmp/logs"
      - "${HOME}/.cache/GPT/:/root/.cache/GPT"
      - "${HOME}/.cache/huggingface/:/root/.cache/huggingface"
    deploy:
      replicas: ${REPLICAS}
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
