version: "3.8"

services:
  redis:
    image: redis:alpine
  rank-counter:
    image: redis:alpine
    depends_on:
      - redis
    command:
      - redis-cli
      - -h
      - redis
      - set
      - rank-counter
      - ${REPLICAS}
  runs-counter:
    image: redis:alpine
    depends_on:
      - redis
    command:
      - redis-cli
      - -h
      - redis
      - set
      - runs-counter
      - ${NUM_RUNS}
  sweep:
    image: ethanabrooks/create-sweep:latest
    depends_on:
      - redis
    volumes:
      - .:/config
    command:
      - --config=/config/config.yml
      - --name=${NAME}
      - --project=gpt-rl
      - --method=${SWEEP_METHOD}
      - redis
    environment:
      - HASURA_URI
      - LOG_PATH
  agent:
    build: .
    depends_on:
      - rank-counter
      - runs-counter
      - sweep
    environment:
      - HOST_MACHINE
      - HASURA_URI
      - LOG_PATH
      - SCRIPT
      - NUM_RUNS
    entrypoint:
      - execute-sweep
    volumes:
      - "${PWD}/logs:/tmp/bsuite"
      - "${HOME}/.cache/GPT/:/root/.cache/GPT"
      - "${HOME}/.cache/huggingface/:/root/.cache/huggingface"
    deploy:
      replicas: ${REPLICAS}
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
