version: "3.8"

services:
  redis:
    image: redis:alpine
  rank-counter:
    image: redis:alpine
    depends_on:
      - redis
    command:
      - redis-cli
      - -h
      - redis
      - set
      - rank-counter
      - ${REPLICAS}
  sweep:
    image: ethanabrooks/create-sweep@sha256:34b00a718054882b022e75980c24ec5ac9a456769ec394b4ea7c0baa87c77bfc
    depends_on:
      - redis
    volumes:
      - .:/config
    command:
      - --config=/config/config.yml
      - --graphql-endpoint=${GRAPHQL_ENDPOINT}
      - --name=${NAME}
      - --project=gpt-rl
      - --method=${SWEEP_METHOD}
      - --remaining-runs=${MAX_RUNS}
      - redis
  agent:
    build: .
    depends_on:
      - rank-counter
      - sweep
    environment:
      - GRAPHQL_ENDPOINT
      - HOST_MACHINE
    entrypoint:
      - execute-sweep
      - --graphql-endpoint=${GRAPHQL_ENDPOINT}
      - --command=python ${SCRIPT} sweep --sweep
    volumes:
      - "${PWD}/logs:/tmp/logs"
      - "${HOME}/.cache/GPT/:/root/.cache/GPT"
      - "${HOME}/.cache/huggingface/:/root/.cache/huggingface"
    deploy:
      replicas: ${REPLICAS}
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
